# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: |
    cd week3/day5/RestaurantReviews
    dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: |
    cd week3/day5/RestaurantReviews
    dotnet test --configuration $(buildConfiguration)
  displayName: 'dotnet test $(buildConfiguration)'
- script: |
    cd week3/day5/RestaurantReviews
    dotnet publish RestaurantReviews.WebApp --configuration $(buildConfiguration) -o ../publish
  displayName: 'dotnet publish $(buildConfiguration)'
