-- tables

CREATE TABLE Products
(
	ID INT IDENTITY NOT NULL,
	Name NVARCHAR(100) NOT NULL,
	Price MONEY NOT NULL,
	CONSTRAINT PK_Products_ID PRIMARY KEY (ID)
)
GO

CREATE TABLE Customers
(
	ID INT IDENTITY NOT NULL,
	Firstname NVARCHAR(100) NOT NULL,
	Lastname NVARCHAR(100) NOT NULL,
	CardNumber VARCHAR(30) NOT NULL,
	CONSTRAINT PK_Customers_ID PRIMARY KEY (ID)
)
GO

CREATE TABLE Orders
(
	ID INT IDENTITY NOT NULL,
	ProductID INT NOT NULL,
	CustomerID INT NOT NULL,
	CONSTRAINT PK_Orders_ID PRIMARY KEY (ID),
	CONSTRAINT FK_Orders_Products_ProductID FOREIGN KEY (ProductID)
		REFERENCES Products (ID),
	CONSTRAINT FK_Orders_Customers_CustomerID FOREIGN KEY (CustomerID)
		REFERENCES Customers (ID)
)
GO

-- add at least 3 records into each table
INSERT INTO Products (Name, Price) VALUES
	('Widget', $30),     -- 1
	('Thingybob', $40),  -- 2
	('Whatsit', $50);    -- 3
INSERT INTO Customers (Firstname, Lastname, CardNumber) VALUES
	('Bill', 'Smith', '4111111111111111'),    -- 1
	('Sarah', 'Smith', '4111111111111112'),   -- 2
	('Arnold', 'Smith', '4111111111111113');  -- 3
INSERT INTO Orders (ProductID, CustomerID) VALUES
	(1, 1),  -- Widget Bill
	(1, 2),  -- Widget Sarah
	(3, 2);  -- Whatsit Sarah

-- add product iPhone priced at $200
INSERT INTO Products (Name, Price) VALUES
	('iPhone', $200);  -- 4

-- add customer Tina Smith
INSERT INTO Customers (Firstname, Lastname, CardNumber) VALUES
	('Tina', 'Smith', '4111111111111114');  -- 4

-- create order for Tina Smith bought an iPhone
INSERT INTO Orders (ProductID, CustomerID) VALUES
	(4, 4);  -- iPhone Tina

-- report all orders by Tina Smith
SELECT p.Name, p.Price
FROM Products AS p
	INNER JOIN Orders AS o ON p.ID = o.ProductID
	INNER JOIN Customers AS c ON o.CustomerID = c.ID
WHERE c.Firstname = 'Tina' AND c.Lastname = 'Smith';

-- report all revenue generated by sales of iPhone
SELECT SUM(Price)
FROM Products AS p
	INNER JOIN Orders AS o ON p.ID = o.ProductID
WHERE Name = 'iPhone';

-- increase the price of iPhone to $250
UPDATE Products
SET Price = $250
WHERE Name = 'iPhone';
